<?php
/**
 * Tradie Sites Co. — trade catalogue.
 * Returns an associative array keyed by URL slug.
 * Each entry supplies name, plural, meta_desc, intro, services[] and faqs[].
 */

return [
    'plumber' => [
        'name' => 'Plumber', 'plural' => 'Plumbers',
        'meta_desc' => 'Plumber website builder — built in 24 hours across Australia. $200 setup + $80/month. Emergency banner, licence display, service areas.',
        'intro' => 'When a hot water system lets go or a pipe bursts, customers reach for Google — not Facebook. Plumbers who show up in local search at 9pm on a Sunday win the emergency jobs at premium rates. We build plumber-specific websites that display your licence, list your service areas, and make the call-now button impossible to miss on a cracked phone screen in a flooded laundry.',
        'services' => [
            'Emergency call-out banner with click-to-call on mobile',
            'Plumbing licence number displayed site-wide for trust',
            'Service area list (suburbs + postcodes) for local SEO',
            'Job gallery — hot water, burst pipes, blocked drains, gas',
            'Quick-quote form that sends straight to your phone',
        ],
        'faqs' => [
            ['q' => 'Can my plumbing licence number be displayed on the site?', 'a' => 'Yes — we put it in the header, footer and contact page. Required by most state authorities and reassures customers you are properly ticketed.'],
            ['q' => 'Will customers be able to call me directly from the site?', 'a' => 'Yes. Every page has a tap-to-call button on mobile, and your phone number is prominent in the nav. On emergency plumbing jobs this is the conversion, not the form.'],
            ['q' => 'Can I show the suburbs I service?', 'a' => 'Yes — you tell us your service area (suburbs, postcodes or a radius) and we build a dedicated page that ranks for "plumber in [suburb]" queries.'],
        ],
    ],
    'electrician' => [
        'name' => 'Electrician', 'plural' => 'Electricians',
        'meta_desc' => 'Electrician website builder — built in 24 hours across Australia. $200 setup + $80/month. Licence display, safety focus, after-hours calls.',
        'intro' => 'Electrical work is life-safety work — and customers searching for an electrician want to see your licence number before they call. We build electrician websites that lead with your credentials, list your service areas, and convert the after-hours panel-trip job into a booked call-out before your competitor even sees the enquiry.',
        'services' => [
            'Electrical licence number displayed in header + footer',
            'After-hours emergency call-out banner',
            'Services page covering switchboards, safety switches, rewires, LED upgrades',
            'Photo gallery of completed commercial and domestic jobs',
            'Click-to-call button pinned to mobile viewport',
        ],
        'faqs' => [
            ['q' => 'Is the licence number displayed prominently?', 'a' => 'Yes — header, footer and contact page. We treat it as the single most important trust element for an electrician website.'],
            ['q' => 'Can I have separate pages for residential and commercial?', 'a' => 'Yes. Within the 5-page build we can split services, and additional service-specific pages are a common add-on.'],
            ['q' => 'Will the site show I do emergency call-outs?', 'a' => 'We put an emergency-services banner at the top of every page and wire it to a dedicated quick-quote form plus your mobile number.'],
        ],
    ],
    'builder' => [
        'name' => 'Builder', 'plural' => 'Builders',
        'meta_desc' => 'Builder website builder — built in 24 hours across Australia. $200 setup + $80/month. Portfolio-led, builder licence, project enquiries.',
        'intro' => 'Builders live and die by their portfolio. When a homeowner is choosing between you and three competitors for a $400k extension, what they see matters as much as what you quote. We build portfolio-led websites for Australian builders — big photos, clear project types, your licence displayed, and a proper enquiry flow that pre-qualifies leads before they reach your phone.',
        'services' => [
            'Full-width project gallery with category filters (new builds, renovations, extensions)',
            'Builder licence number in header + footer',
            'Project enquiry form capturing budget, timeframe and site address',
            'Before/after comparison images for renovations',
            'Testimonial-ready layout (we leave slots; you fill with real client quotes)',
        ],
        'faqs' => [
            ['q' => 'Can I show off specific project types — renovations, new builds, extensions?', 'a' => 'Yes. Your gallery is segmented into project types so a customer looking for a second-storey addition can see only that work.'],
            ['q' => 'How many project photos can I include?', 'a' => 'No hard cap. We usually load 20–40 photos at launch and add more as part of your monthly gallery updates.'],
            ['q' => 'Can enquiries capture budget and timeframe?', 'a' => 'Yes — the enquiry form asks for indicative budget, timeframe and site location so you spend time on real leads, not tyre-kickers.'],
        ],
    ],
    'painter' => [
        'name' => 'Painter', 'plural' => 'Painters',
        'meta_desc' => 'Painter website builder — built in 24 hours across Australia. $200 setup + $80/month. Before/after gallery, interior + exterior jobs, free quotes.',
        'intro' => 'Painting is the most visual trade there is — so your website had better be too. A one-line Facebook page with a blurry drop-sheet photo loses every time to a painter with a proper gallery. We build painter websites built around a high-impact before/after gallery, with clear interior vs exterior service pages and a free-quote form that converts browsers into booked site visits.',
        'services' => [
            'Before/after slider gallery (residential + commercial)',
            'Interior and exterior services split into dedicated sections',
            'Colour consultation enquiry flow',
            'Free-quote form with photo upload',
            'Service area page for local suburbs',
        ],
        'faqs' => [
            ['q' => 'Can I show before/after on the same image?', 'a' => 'Yes — we use a draggable before/after slider that instantly communicates the transformation. It converts much harder than separate photos.'],
            ['q' => 'Can customers upload photos when requesting a quote?', 'a' => 'Yes. The quote form accepts photo uploads so you can price jobs accurately without a site visit for smaller work.'],
            ['q' => 'Do you cover both residential and commercial painting?', 'a' => 'Yes. We split the two into separate sections so commercial property managers and homeowners each see content relevant to them.'],
        ],
    ],
    'concreter' => [
        'name' => 'Concreter', 'plural' => 'Concreters',
        'meta_desc' => 'Concreter website builder — built in 24 hours across Australia. $200 setup + $80/month. Driveways, slabs, decorative concrete, quote requests.',
        'intro' => 'Concreting jobs — driveways, slabs, exposed aggregate, decorative — are all googled locally and intensively price-shopped. We build concreter websites that show your finish quality in photos, list the styles you pour, and make it easy for a homeowner to request a quote with a site measurement and photos attached.',
        'services' => [
            'Gallery split by finish type (plain, exposed aggregate, stamped, coloured)',
            'Driveway, slab and pathway service pages',
            'Quote form with square-metre input and photo upload',
            'Service area map of suburbs you pour in',
            'Timeline block explaining the pour process',
        ],
        'faqs' => [
            ['q' => 'Can the site show different concrete finishes separately?', 'a' => 'Yes. The gallery is tagged by finish so customers looking for exposed aggregate only see that work.'],
            ['q' => 'Can I ask for square metres in the quote form?', 'a' => 'Yes — we add a sqm field and optional photo upload so you can ballpark pricing before a site visit.'],
            ['q' => 'Do you build sites for commercial concreters as well?', 'a' => 'Yes. We can lead with commercial case studies and tailor the enquiry flow to project managers rather than homeowners.'],
        ],
    ],
    'tiler' => [
        'name' => 'Tiler', 'plural' => 'Tilers',
        'meta_desc' => 'Tiler website builder — built in 24 hours across Australia. $200 setup + $80/month. Bathroom + kitchen galleries, waterproofing, free quotes.',
        'intro' => 'Tiling is won on the finish. A single photo of a crooked grout line loses the job; a sharp bathroom shot wins it. We build tiler websites with big, lightbox-friendly galleries split by room type, clear waterproofing credentials, and a quote flow that lets customers share a floor plan or room photo right from their phone.',
        'services' => [
            'Bathroom, kitchen, laundry and outdoor gallery sections',
            'Waterproofing credentials and certifications displayed',
            'Free measure-and-quote form with photo upload',
            'Tile-style inspiration section (subway, herringbone, large-format, mosaic)',
            'Service area list for local SEO',
        ],
        'faqs' => [
            ['q' => 'Can the gallery be split by room?', 'a' => 'Yes — bathroom, kitchen, laundry and outdoor are separate tabs so browsers find what they want immediately.'],
            ['q' => 'Can I display my waterproofing credentials?', 'a' => 'Yes. We show certification numbers and a dedicated waterproofing page since it is one of the biggest trust factors for customers renovating a bathroom.'],
            ['q' => 'Do you cover commercial tiling as well?', 'a' => 'Yes. Commercial projects can have their own section if that is part of your mix.'],
        ],
    ],
    'landscaper' => [
        'name' => 'Landscaper', 'plural' => 'Landscapers',
        'meta_desc' => 'Landscaper website builder — built in 24 hours across Australia. $200 setup + $80/month. Design portfolio, softscape + hardscape, enquiry flow.',
        'intro' => 'Landscaping is sold on vision. Customers who are considering a $40k backyard transformation need to see what you can do before they even open the phone. We build landscaper websites that lead with a rich design portfolio, split softscape and hardscape services, and give customers a clear path from inspiration to design consultation.',
        'services' => [
            'Full-width design portfolio with project deep-dives',
            'Softscape vs hardscape service split (turf, planting vs pavers, retaining)',
            'Design consultation booking flow',
            'Seasonal maintenance service page',
            'Before/after transformation gallery',
        ],
        'faqs' => [
            ['q' => 'Can I show designs vs completed projects?', 'a' => 'Yes. Each project listing supports concept renders and the completed build so customers see both sides of your service.'],
            ['q' => 'Can customers book a design consult online?', 'a' => 'Yes. The enquiry flow includes a simple consultation booking form with preferred times.'],
            ['q' => 'Do you handle ongoing maintenance clients too?', 'a' => 'Yes. We include a dedicated maintenance page so repeat-revenue customers find you as well as one-off designs.'],
        ],
    ],
    'fencer' => [
        'name' => 'Fencer', 'plural' => 'Fencers',
        'meta_desc' => 'Fencer website builder — built in 24 hours across Australia. $200 setup + $80/month. Colorbond, timber, pool fencing, free metre-rate quotes.',
        'intro' => 'Fencing is one of the most price-shopped trades in Australia — customers compare three quotes on metre rates before calling. We build fencer websites that pre-answer the common questions (Colorbond, timber, pool, commercial), show real completed runs in the gallery, and capture lineal metres plus a photo in the quote form so you can price jobs without driving out.',
        'services' => [
            'Gallery split by fence type — Colorbond, timber, aluminium, pool, commercial',
            'Quote form with lineal-metre input and photo upload',
            'Service area page for local suburbs',
            'Pool fencing compliance page (AS 1926-1 reference)',
            'Before/after removal-and-replace section',
        ],
        'faqs' => [
            ['q' => 'Can the site capture lineal metres in the quote form?', 'a' => 'Yes — a simple lineal-metre field plus photo upload lets you quote most residential jobs without a site visit.'],
            ['q' => 'Do you cover pool fencing compliance?', 'a' => 'Yes. We include a dedicated pool-fence page referencing AS 1926-1 and your compliance credentials.'],
            ['q' => 'Can I show the difference between Colorbond, timber and aluminium?', 'a' => 'Yes — the gallery is tagged by fence type with pricing indicators so customers self-qualify before enquiring.'],
        ],
    ],
    'roofer' => [
        'name' => 'Roofer', 'plural' => 'Roofers',
        'meta_desc' => 'Roofer website builder — built in 24 hours across Australia. $200 setup + $80/month. Repairs, restoration, replacements, emergency call-outs.',
        'intro' => 'Roofing splits into three very different customer journeys: urgent leaks, planned restorations, and full replacements. Each one wants a different pitch. We build roofer websites that route emergency enquiries to your phone immediately, sell restoration jobs with before/after photos, and qualify replacement jobs with budget and timing questions.',
        'services' => [
            'Emergency leak call-out banner with click-to-call',
            'Restoration before/after gallery',
            'Full roof replacement project case studies',
            'Tile, metal and Colorbond service pages',
            'Roof inspection booking form',
        ],
        'faqs' => [
            ['q' => 'Can I show repairs, restoration and replacement as separate services?', 'a' => 'Yes. Three distinct service pages with their own photo galleries and enquiry forms.'],
            ['q' => 'Does the site handle emergency leak calls out of hours?', 'a' => 'Yes — a persistent emergency banner on every page drives straight to your mobile after hours.'],
            ['q' => 'Can I book a roof inspection through the site?', 'a' => 'Yes. A short inspection form captures address, roof type and issue so you can schedule efficiently.'],
        ],
    ],
    'air-conditioning' => [
        'name' => 'Air Conditioning Installer', 'plural' => 'Air Conditioning Installers',
        'meta_desc' => 'Air conditioning website builder — built in 24 hours across Australia. $200 setup + $80/month. Install, service, brands, free quotes.',
        'intro' => 'Air conditioning is a two-season business — and every customer search happens in a heatwave or a cold snap. We build AC installer websites that rank locally year-round, list the brands you install and service (Daikin, Mitsubishi, Fujitsu, Panasonic), and make the quote-a-split-system flow take less than two minutes on a sweltering Monday.',
        'services' => [
            'Split system quote form with room-size calculator',
            'Supported brands page (Daikin, Mitsubishi, Fujitsu, Panasonic, LG)',
            'Ducted vs split system comparison page',
            'Service and repair booking flow',
            'Seasonal tune-up promotion slot',
        ],
        'faqs' => [
            ['q' => 'Can I list the brands I install?', 'a' => 'Yes — a dedicated brands page lets customers filter by their preferred manufacturer.'],
            ['q' => 'Does the quote form ask about room size?', 'a' => 'Yes. Room-size (sqm) helps you recommend a kW rating in your reply, which converts faster than a generic quote request.'],
            ['q' => 'Can I show service and install as separate offerings?', 'a' => 'Yes. Two distinct flows so existing-system service calls go to one queue and new installs go to another.'],
        ],
    ],
    'carpenter' => [
        'name' => 'Carpenter', 'plural' => 'Carpenters',
        'meta_desc' => 'Carpenter website builder — built in 24 hours across Australia. $200 setup + $80/month. Decks, pergolas, custom joinery, built-ins.',
        'intro' => 'Carpenters do everything from a fixed cupboard door to a full second-storey frame — and customers need to know which jobs you take on. We build carpenter websites that clearly show your service mix (decks, pergolas, built-ins, renovations), lead with a portfolio of finished work, and route small repair calls differently to major project enquiries.',
        'services' => [
            'Service list covering decks, pergolas, built-ins, doors, frames',
            'Project gallery with category filters',
            'Quote form split by job size (small repair vs full project)',
            'Materials and finishes reference page',
            'Service area for local suburbs',
        ],
        'faqs' => [
            ['q' => 'Can I show what kinds of carpentry I do?', 'a' => 'Yes — the service list covers decks, pergolas, built-ins, doors, framing and renovations, with a gallery per category.'],
            ['q' => 'Does the site route small jobs differently to big projects?', 'a' => 'Yes. The enquiry form splits into quick repair vs project so you can triage replies.'],
            ['q' => 'Can I add my own project photos over time?', 'a' => 'Yes — gallery photo updates are part of your monthly plan.'],
        ],
    ],
    'pest-control' => [
        'name' => 'Pest Control Technician', 'plural' => 'Pest Control Technicians',
        'meta_desc' => 'Pest control website builder — built in 24 hours across Australia. $200 setup + $80/month. Termite, rodent, cockroach treatments, warranties.',
        'intro' => 'Pest control sells on urgency and warranty. When someone finds a cockroach, they want a treatment today — and they want to know you will come back if the problem returns. We build pest control websites that book same-day treatments, list your pest-specific services (termite, rodent, cockroach, spider), and prominently display your warranty terms.',
        'services' => [
            'Same-day booking flow with preferred time slots',
            'Pest-specific service pages (termite, rodent, cockroach, spider, ant)',
            'Warranty and guarantee terms prominently displayed',
            'Pre-purchase termite inspection request form',
            'Commercial vs residential treatment split',
        ],
        'faqs' => [
            ['q' => 'Can customers book same-day treatments?', 'a' => 'Yes. The booking flow asks for preferred time slots and sends an SMS/email notification to you immediately.'],
            ['q' => 'Does the site display my warranty terms?', 'a' => 'Yes — prominent on every service page, because it is the biggest conversion lever in pest control.'],
            ['q' => 'Can I offer pre-purchase termite inspections?', 'a' => 'Yes. A dedicated form captures property address and settlement timeframe.'],
        ],
    ],
    'cleaner' => [
        'name' => 'Cleaner', 'plural' => 'Cleaners',
        'meta_desc' => 'Cleaner website builder — built in 24 hours across Australia. $200 setup + $80/month. Residential, commercial, end-of-lease, bond-back guarantees.',
        'intro' => 'Cleaning splits into three totally different customer journeys: regular residential, commercial contracts, and end-of-lease (which is googled hardest). We build cleaner websites that capture each properly, list bond-back guarantees, and book recurring or one-off jobs through a simple form that asks the right qualifying questions.',
        'services' => [
            'Residential, commercial and end-of-lease service pages',
            'Bond-back guarantee prominently displayed',
            'Quote form with bedroom/bathroom count and frequency',
            'Service area list',
            'Recurring booking option (weekly, fortnightly, monthly)',
        ],
        'faqs' => [
            ['q' => 'Can I show the bond-back guarantee?', 'a' => 'Yes — it is a headline trust element on the end-of-lease page, which is the highest-intent search in cleaning.'],
            ['q' => 'Can customers book recurring jobs?', 'a' => 'Yes. The booking form offers one-off, weekly, fortnightly or monthly options.'],
            ['q' => 'Does the site handle commercial contract enquiries?', 'a' => 'Yes — a separate commercial enquiry flow captures site type, square metres and frequency.'],
        ],
    ],
    'handyman' => [
        'name' => 'Handyman', 'plural' => 'Handymen',
        'meta_desc' => 'Handyman website builder — built in 24 hours across Australia. $200 setup + $80/month. Small jobs, list of services, quick quotes.',
        'intro' => 'Handyman work is all about a long list of small jobs — and a customer who finds a tradie willing to do the four things on their list in one visit converts instantly. We build handyman websites that lead with an exhaustive services list, capture multi-job enquiries with photo uploads, and let you accept or decline jobs based on what is in the photos.',
        'services' => [
            'Exhaustive services checklist (assembly, TV mount, door repair, decking, minor electrical exclusions, etc.)',
            'Multi-job quote form with per-job photo upload',
            'Hourly rate and minimum-callout transparency',
            'Service area with suburb list',
            'Before/after gallery',
        ],
        'faqs' => [
            ['q' => 'Can customers list multiple jobs in one quote?', 'a' => 'Yes — the form supports a multi-item list with per-item photos so you can price and schedule the visit properly.'],
            ['q' => 'Can I show my hourly rate and minimum call-out?', 'a' => 'Yes. Transparent pricing reduces wasted calls from customers below your minimum.'],
            ['q' => 'Can the site exclude jobs I will not do (like electrical)?', 'a' => 'Yes. We explicitly list exclusions so customers do not book jobs that need a ticketed tradie.'],
        ],
    ],
    'glazier' => [
        'name' => 'Glazier', 'plural' => 'Glaziers',
        'meta_desc' => 'Glazier website builder — built in 24 hours across Australia. $200 setup + $80/month. Emergency glass, shopfronts, windows, insurance claims.',
        'intro' => 'Most glass jobs are emergencies — a smashed window at midnight, a storm-damaged shopfront at 6am. We build glazier websites with a persistent emergency banner, a dedicated insurance-claim path, and service pages for windows, shopfronts, showers and balustrades so every customer type finds what they need fast.',
        'services' => [
            'Emergency glass call-out banner with click-to-call',
            'Insurance claim support page with document requirements',
            'Shopfront, residential window, shower and balustrade service split',
            'Quote form with photo upload',
            'After-hours booking flow',
        ],
        'faqs' => [
            ['q' => 'Do you handle after-hours emergency glass calls?', 'a' => 'Yes — a persistent banner drives straight to your mobile.'],
            ['q' => 'Can the site support insurance claim enquiries?', 'a' => 'Yes. A dedicated page lists the document requirements insurers commonly need and a claim-specific enquiry form.'],
            ['q' => 'Can I show both residential and commercial work?', 'a' => 'Yes — shopfronts and residential windows have their own pages and galleries.'],
        ],
    ],
    'plasterer' => [
        'name' => 'Plasterer', 'plural' => 'Plasterers',
        'meta_desc' => 'Plasterer website builder — built in 24 hours across Australia. $200 setup + $80/month. Gyprock, cornice, ceiling repairs, water damage.',
        'intro' => 'Plastering sells on clean finish photos — perfect cornices, flush patches, smooth ceilings. We build plasterer websites that lead with a finish-focused gallery, cover common repair jobs (water damage, ceiling crack, sagging plaster), and give customers a simple "send us a photo" quote flow that cuts the site-visit cycle in half.',
        'services' => [
            'Gallery split by finish (cornice, set, patch, new installation)',
            'Water damage and ceiling repair service pages',
            'Photo-first quote flow',
            'Service area page',
            'Gyprock vs plasterboard explainer',
        ],
        'faqs' => [
            ['q' => 'Can I show my cornice work separately to flat finishing?', 'a' => 'Yes — the gallery is tagged so cornice specialists can lead with that work.'],
            ['q' => 'Can customers send a photo of the damage for a quote?', 'a' => 'Yes. Photo uploads are standard on the quote form and let you price small patch jobs without a site visit.'],
            ['q' => 'Do you cover commercial plastering?', 'a' => 'Yes. If commercial is part of your mix it gets its own service page and case studies.'],
        ],
    ],
    'flooring' => [
        'name' => 'Flooring Specialist', 'plural' => 'Flooring Specialists',
        'meta_desc' => 'Flooring website builder — built in 24 hours across Australia. $200 setup + $80/month. Timber, laminate, vinyl, carpet, measure-and-quote.',
        'intro' => 'Flooring is a big-ticket, highly visual purchase — and customers research for weeks before calling. We build flooring websites with rich product-type galleries (timber, laminate, vinyl, carpet), a clear measure-and-quote process, and sample-request forms that keep your business in front of prospects through their research phase.',
        'services' => [
            'Galleries per product type (engineered timber, laminate, LVP, carpet, hybrid)',
            'Measure-and-quote booking form',
            'Sample request flow',
            'Installation vs supply-only clarity',
            'Service area page',
        ],
        'faqs' => [
            ['q' => 'Can the site cover different flooring types separately?', 'a' => 'Yes. Each product type has its own page with a gallery and spec notes.'],
            ['q' => 'Can customers request product samples?', 'a' => 'Yes — a sample request form keeps you in front of customers during their decision phase.'],
            ['q' => 'Can I offer supply-only and install-only options?', 'a' => 'Yes. The quote flow lets customers select install, supply-only or both.'],
        ],
    ],
    'solar-installer' => [
        'name' => 'Solar Installer', 'plural' => 'Solar Installers',
        'meta_desc' => 'Solar installer website builder — built in 24 hours across Australia. $200 setup + $80/month. Panels, inverters, batteries, rebates.',
        'intro' => 'Solar is a rebate-driven, confidence-heavy sale — customers want to know what they will save, what rebates apply, and whether your installation will still be good in ten years. We build solar installer websites that publish live federal and state rebate info, list the brands you install, and give customers a quote flow that qualifies roof type, orientation and usage.',
        'services' => [
            'Rebate information page (federal STC + state incentives where applicable)',
            'Brand pages for panels, inverters and batteries',
            'System design enquiry form (roof type, quarterly bill, usage hours)',
            'Case studies of completed installs with generation data',
            'CEC-accredited installer credentials displayed',
        ],
        'faqs' => [
            ['q' => 'Can the site show current rebates?', 'a' => 'Yes. We include a rebates page and update it as part of your monthly edits when federal or state policy changes.'],
            ['q' => 'Can I list the panel and inverter brands I install?', 'a' => 'Yes — dedicated brand pages help you rank for brand-specific searches.'],
            ['q' => 'Can I display my CEC accreditation?', 'a' => 'Yes. Your accreditation is displayed in the header and footer — it is the single biggest trust lever for solar customers.'],
        ],
    ],
    'locksmith' => [
        'name' => 'Locksmith', 'plural' => 'Locksmiths',
        'meta_desc' => 'Locksmith website builder — built in 24 hours across Australia. $200 setup + $80/month. 24/7 call-outs, rekey, auto, commercial.',
        'intro' => 'Locksmithing is almost entirely emergency work — locked out at 2am, broken key in the ignition, office lockout on a Monday morning. We build locksmith websites where the call-now button never leaves the top of the screen, the 24/7 promise is front and centre, and the ETA and call-out fee are transparent before the customer even reads the rest of the site.',
        'services' => [
            '24/7 emergency call-out banner with click-to-call',
            'Transparent call-out fee and ETA display',
            'Service pages for residential, commercial and automotive lockouts',
            'Rekey and master-key systems page',
            'Coverage area map',
        ],
        'faqs' => [
            ['q' => 'Can the site make the 24/7 promise prominent?', 'a' => 'Yes — it is the whole point. A persistent banner with tap-to-call sits above every section.'],
            ['q' => 'Can I show call-out fee and ETA?', 'a' => 'Yes. Transparent pricing saves time on calls that would have been out of scope anyway.'],
            ['q' => 'Does the site cover car lockouts?', 'a' => 'Yes — a dedicated automotive page covers key extraction, transponder programming and key replacement.'],
        ],
    ],
    'pool-builder' => [
        'name' => 'Pool Builder', 'plural' => 'Pool Builders',
        'meta_desc' => 'Pool builder website builder — built in 24 hours across Australia. $200 setup + $80/month. Concrete, fibreglass, plunge pools, design consults.',
        'intro' => 'Pool builds are one of the most considered purchases a homeowner makes — six-figure projects researched over months. We build pool builder websites that lead with your completed pools in big, cinematic photos, cover concrete vs fibreglass clearly, and convert browsers into design consultations with qualification questions up front.',
        'services' => [
            'Full-width pool project gallery with builds (concrete, fibreglass, plunge)',
            'Design consultation booking flow',
            'Concrete vs fibreglass comparison page',
            'Pool fencing compliance note (AS 1926-1)',
            'Builder licence displayed prominently',
        ],
        'faqs' => [
            ['q' => 'Can I show concrete and fibreglass pools separately?', 'a' => 'Yes — each has its own gallery and service page.'],
            ['q' => 'Can customers book a design consultation?', 'a' => 'Yes. The consultation flow asks site details and preferred times.'],
            ['q' => 'Is pool fencing compliance covered?', 'a' => 'Yes. A dedicated page references AS 1926-1 so customers know what they are signing up for.'],
        ],
    ],
    'demolition' => [
        'name' => 'Demolition Contractor', 'plural' => 'Demolition Contractors',
        'meta_desc' => 'Demolition website builder — built in 24 hours across Australia. $200 setup + $80/month. Residential, commercial, waste disposal, permits.',
        'intro' => 'Demolition is licence-heavy, safety-critical work — and customers need to trust you handle the permits, asbestos and waste. We build demolition websites that lead with your credentials, split residential and commercial work, and make it easy for a developer or homeowner to request a quote with site details and timeline.',
        'services' => [
            'Licence and insurance credentials displayed prominently',
            'Residential vs commercial demolition service pages',
            'Asbestos removal page (licensed removers only)',
            'Waste disposal and recycling information',
            'Quote form with site address and timeline',
        ],
        'faqs' => [
            ['q' => 'Are licence and insurance shown clearly?', 'a' => 'Yes — header, footer and dedicated credentials page.'],
            ['q' => 'Can I offer asbestos removal as a separate service?', 'a' => 'Yes, if you hold the required licence. We make the licence number prominent.'],
            ['q' => 'Can the site handle commercial project enquiries?', 'a' => 'Yes. A separate enquiry flow captures developer-level details (site address, timeline, volume).'],
        ],
    ],
    'arborist' => [
        'name' => 'Arborist', 'plural' => 'Arborists',
        'meta_desc' => 'Arborist website builder — built in 24 hours across Australia. $200 setup + $80/month. Tree removal, pruning, stump grinding, reports.',
        'intro' => 'Arborist work spans urgent storm removals and planned pruning — two different customer urgencies. We build arborist websites with an emergency storm-response banner, clear services (removal, pruning, stump grinding, arborist reports), and a quote form that accepts a photo of the tree so you can price without always visiting.',
        'services' => [
            'Emergency storm-damage banner',
            'Services: removal, pruning, stump grinding, arborist reports',
            'Quote form with tree photo and access notes',
            'Certified arborist credentials displayed',
            'Council-report page for development applications',
        ],
        'faqs' => [
            ['q' => 'Do you handle emergency storm call-outs?', 'a' => 'Yes — a banner on every page drives straight to your mobile.'],
            ['q' => 'Can I show my arborist certifications?', 'a' => 'Yes. Certifications are displayed site-wide and a dedicated credentials page goes deeper.'],
            ['q' => 'Can I offer council arborist reports for DA applications?', 'a' => 'Yes — a separate page covers report requirements and pricing.'],
        ],
    ],
    'pressure-washing' => [
        'name' => 'Pressure Washing Specialist', 'plural' => 'Pressure Washers',
        'meta_desc' => 'Pressure washing website builder — built in 24 hours across Australia. $200 setup + $80/month. Driveways, exteriors, roofs, before/after.',
        'intro' => 'Pressure washing is the ultimate before/after trade — the photos sell themselves. We build pressure washing websites around a heavy before/after gallery, service pages for driveways, exteriors, roofs and commercial, and an instant-quote flow that asks for a photo and square metres.',
        'services' => [
            'Before/after slider gallery site-wide',
            'Services: driveway, exterior, roof, commercial, graffiti',
            'Quick-quote form with sqm and photo upload',
            'Eco-friendly chemical information page',
            'Service area map',
        ],
        'faqs' => [
            ['q' => 'Is the before/after slider included?', 'a' => 'Yes — it is the highest-converting element for pressure washing and runs on every service page.'],
            ['q' => 'Can customers upload a photo in the quote?', 'a' => 'Yes. Photo plus sqm gets you most residential jobs quoted remotely.'],
            ['q' => 'Do you cover commercial clients too?', 'a' => 'Yes. A separate commercial page handles recurring contract enquiries.'],
        ],
    ],
    'irrigation' => [
        'name' => 'Irrigation Specialist', 'plural' => 'Irrigation Specialists',
        'meta_desc' => 'Irrigation website builder — built in 24 hours across Australia. $200 setup + $80/month. Garden reticulation, smart controllers, service.',
        'intro' => 'Irrigation systems are a mix of design-build and ongoing service — and customers want to know you understand their yard, soil and local watering restrictions. We build irrigation websites that lead with before/after of installed systems, cover smart controllers and retic, and route service requests differently to new installs.',
        'services' => [
            'New system design and install service pages',
            'Smart controller setup (Rachio, Hunter Hydrawise)',
            'Service and fault-finding booking flow',
            'Local watering-restriction awareness page',
            'Residential vs commercial garden systems',
        ],
        'faqs' => [
            ['q' => 'Do you cover smart controllers?', 'a' => 'Yes — a dedicated page covers Rachio, Hunter Hydrawise and the savings they drive on water bills.'],
            ['q' => 'Can service calls be booked separately to new installs?', 'a' => 'Yes. Two enquiry flows so service and install go into separate queues.'],
            ['q' => 'Do you cover commercial landscape irrigation?', 'a' => 'Yes. If commercial is part of your mix it gets its own page.'],
        ],
    ],
    'gas-fitter' => [
        'name' => 'Gas Fitter', 'plural' => 'Gas Fitters',
        'meta_desc' => 'Gas fitter website builder — built in 24 hours across Australia. $200 setup + $80/month. Licence, gas safety, compliance certificates.',
        'intro' => 'Gas fitting is life-safety work with strict licensing — customers need to see your licence before they let you anywhere near their gas line. We build gas fitter websites with licence number displayed site-wide, gas compliance certificate service page, and a clear emergency gas-leak response path.',
        'services' => [
            'Gas licence number displayed in header + footer',
            'Emergency gas-leak response banner',
            'Gas compliance certificate page for property sales',
            'Cooktop, hot water and heater install service pages',
            'Service area map',
        ],
        'faqs' => [
            ['q' => 'Is my gas licence shown prominently?', 'a' => 'Yes — header, footer and credentials page. Compulsory for customer trust in gas work.'],
            ['q' => 'Do you handle compliance certificates for property sales?', 'a' => 'Yes. A dedicated page explains the compliance cert process and a booking form captures property address and settlement date.'],
            ['q' => 'Can the site route emergency gas-leak calls?', 'a' => 'Yes — a persistent emergency banner drives straight to your mobile.'],
        ],
    ],
    'concrete-cutter' => [
        'name' => 'Concrete Cutter', 'plural' => 'Concrete Cutters',
        'meta_desc' => 'Concrete cutter website builder — built in 24 hours across Australia. $200 setup + $80/month. Saw cutting, coring, demolition support.',
        'intro' => 'Concrete cutting is a specialist trade that mostly serves other trades — builders, electricians, plumbers and demolition contractors. We build concrete cutter websites that speak directly to tradies first, show equipment capabilities (saw depth, core diameters), and capture trade-to-trade enquiries with the technical details upfront.',
        'services' => [
            'Equipment capabilities page (saw depth, core diameter range, wall saw)',
            'Services: saw cutting, core drilling, wall sawing, hand sawing',
            'Trade-to-trade enquiry form with site address and cut specs',
            'Emergency same-day call-out banner',
            'Waste slurry management page',
        ],
        'faqs' => [
            ['q' => 'Can I list my equipment specs?', 'a' => 'Yes — saw depths, core diameters and reach details so trade customers self-qualify before enquiring.'],
            ['q' => 'Can the enquiry form capture cut specs?', 'a' => 'Yes. The form asks for cut type, depth, length and site access so you can quote and schedule.'],
            ['q' => 'Do you cover same-day trade call-outs?', 'a' => 'Yes — a dedicated banner for urgent trade support jobs.'],
        ],
    ],
    'scaffolding' => [
        'name' => 'Scaffolding Contractor', 'plural' => 'Scaffolding Contractors',
        'meta_desc' => 'Scaffolding website builder — built in 24 hours across Australia. $200 setup + $80/month. Residential, commercial, hire and erect.',
        'intro' => 'Scaffolding serves builders, roofers, painters and commercial sites — all with different scale needs. We build scaffolding websites that split residential and commercial clearly, display your safety credentials, and make it easy for a project manager to request a quote with site dimensions and duration.',
        'services' => [
            'Residential vs commercial scaffolding service split',
            'Safety credentials and high-risk work licence displayed',
            'Quote form with site address, height and duration',
            'Hire-only vs hire-and-erect clarity',
            'Completed project gallery',
        ],
        'faqs' => [
            ['q' => 'Can I show residential and commercial separately?', 'a' => 'Yes. Two service flows so different customer types see relevant content.'],
            ['q' => 'Is the high-risk work licence displayed?', 'a' => 'Yes — it is the single biggest trust element for scaffolding customers.'],
            ['q' => 'Can the quote capture duration?', 'a' => 'Yes. Site address, height and hire duration are captured upfront.'],
        ],
    ],
    'waterproofing' => [
        'name' => 'Waterproofing Specialist', 'plural' => 'Waterproofing Specialists',
        'meta_desc' => 'Waterproofing website builder — built in 24 hours across Australia. $200 setup + $80/month. Balconies, wet areas, rooftops, compliance.',
        'intro' => 'Waterproofing is invisible when it works and catastrophic when it fails — customers need to trust your compliance and warranty. We build waterproofing websites that lead with your certifications, split the three main job types (wet areas, balconies, roofs), and make the warranty terms crystal clear.',
        'services' => [
            'Certifications and warranty terms displayed prominently',
            'Wet area, balcony and rooftop service pages',
            'Remediation and leak-repair service flow',
            'Product types explained (liquid membranes, sheet systems)',
            'Commercial project case studies',
        ],
        'faqs' => [
            ['q' => 'Are certifications shown clearly?', 'a' => 'Yes — displayed site-wide because compliance is the whole game in waterproofing.'],
            ['q' => 'Can I split wet areas from balconies and roofs?', 'a' => 'Yes. Three service pages so each customer type finds relevant content.'],
            ['q' => 'Do you cover warranty terms?', 'a' => 'Yes. Warranty is one of the most-asked questions so it gets its own page.'],
        ],
    ],
    'renderer' => [
        'name' => 'Renderer', 'plural' => 'Renderers',
        'meta_desc' => 'Renderer website builder — built in 24 hours across Australia. $200 setup + $80/month. Cement, acrylic, texture, full facade renders.',
        'intro' => 'Rendering transforms a facade — and that transformation is the entire sales pitch. We build renderer websites that lead with dramatic before/after of full facade jobs, split cement from acrylic and texture, and give customers a square-metre-based quote flow with a photo upload.',
        'services' => [
            'Before/after facade gallery site-wide',
            'Cement vs acrylic vs texture render explainer',
            'Quote form with sqm and facade photo',
            'Colour and finish inspiration page',
            'Commercial and residential project split',
        ],
        'faqs' => [
            ['q' => 'Can the site show full-facade before/after?', 'a' => 'Yes — large before/after imagery is the whole conversion engine for renderers.'],
            ['q' => 'Can I explain the difference between cement and acrylic?', 'a' => 'Yes. A comparison page helps customers self-qualify before they call.'],
            ['q' => 'Can customers send a photo of the facade?', 'a' => 'Yes — photo plus sqm lets you quote most residential jobs without a site visit.'],
        ],
    ],
    'general-tradie' => [
        'name' => 'General Tradie', 'plural' => 'General Tradies',
        'meta_desc' => 'General tradie website builder — built in 24 hours across Australia. $200 setup + $80/month. Multi-skilled, small jobs, home maintenance.',
        'intro' => 'If you cover a broad mix — small repairs, maintenance, installs across a few trades — you need a site that clearly lists the full range without feeling generic. We build general tradie websites that lead with your services checklist, capture multi-job enquiries with photos, and let you accept or decline based on what you see in the request.',
        'services' => [
            'Broad services checklist covering your actual mix',
            'Multi-job quote form with photo upload per item',
            'Hourly rate and minimum-callout clarity',
            'Before/after gallery',
            'Service area with suburb list',
        ],
        'faqs' => [
            ['q' => 'Can I list all the trades I cover?', 'a' => 'Yes — your services checklist is tailored to what you actually do, with clear exclusions for what you do not.'],
            ['q' => 'Can customers send multiple jobs in one quote?', 'a' => 'Yes. The form supports a multi-item list with photos so you can triage the visit properly.'],
            ['q' => 'Can I show my hourly rate?', 'a' => 'Yes. Transparent pricing filters out below-minimum enquiries.'],
        ],
    ],
];
